In [4]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
import numpy as np

In [5]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

display(x_data)

tensor([[1, 2],
        [3, 4]])

In [9]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
display(rand_tensor)
#张量的维度输出
ones_tensor = torch.ones(shape)
display(ones_tensor)
zeros_tensor = torch.zeros(shape)
display(zeros_tensor)

tensor([[0.9496, 0.2733, 0.5336],
        [0.0489, 0.5208, 0.6069]])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
#下面写一个张量属性
tensor = torch.rand(3,4)
display(tensor.shape)
display(tensor.dtype)
display(tensor.device)

torch.Size([3, 4])

torch.float32

device(type='cpu')

In [23]:
#切片
tensor = torch.ones(4,4)
display(tensor)
display(tensor[0])
display(tensor[:0])#这个相当于把第一行变成0
tensor[:1] = 0
display(tensor)
tensor[:,1] = 0
display(tensor)
tensor[:,3] = 4
#后面是下标列的意思
display(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([1., 1., 1., 1.])

tensor([], size=(0, 4))

tensor([[0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

tensor([[0., 0., 0., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.],
        [1., 0., 1., 4.]])

In [27]:
t = torch.ones(5)
display(t)
n = t.numpy()
display(n)
# 也就是说这两个都是相同的
# 也可以整体加1
t.add_(2)
display(np.add(n,1,out = n))

tensor([1., 1., 1., 1., 1.])

array([1., 1., 1., 1., 1.], dtype=float32)

array([4., 4., 4., 4., 4.], dtype=float32)